### PR TITLE
push release as part of container node

### PR DESCRIPTION
**Pull request by de-code**
I was sure there was something missing..
(apart from the master branch)

It's not finding the image since the push release steps are not run on the container node.
I guess the merge with master and downstream steps don't need to be run from the container node but is there any harm in doing so?

fix for #84

### CODE REVIEW

**Comment by de-code** [comment]
Might need to add permissions:

```
10:08:54 + git push origin master
10:08:54 Permission denied (publickey).
```

**Comment by giorgiosironi** [comment]
Starting from https://github.com/elifesciences/builder-base-formula/pull/184 but will take a while.

**Comment by de-code** [comment]
Okay, thank you. As much as I would like it to be done, it's not urgent.

**Comment by giorgiosironi** [comment]
Can give the credentials to `container` stacks, but run into a problem where [AMIs are stripped of credentials](https://github.com/elifesciences/builder/blob/master/scripts/clean-stack-for-ami.sh#L21). That makes sense when we use the AMI of `basebox` to quickly create other project servers, and as a precaution, but in this case the AMI is directly used by Jenkins so it's like a binary artifact to deploy.

Can probably write an init script to pull these credentials from somewhere, or to decrypt them, but would just move the problem to a "master key" that can be used to retrieve/decrypt them without added security.

/cc @lsh-0

**Pull request merged**
